#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 5

enum {
  sym_identifier = 1,
  anon_sym_where = 2,
  anon_sym_which = 3,
  anon_sym_map = 4,
  anon_sym_limit = 5,
  anon_sym_order = 6,
  anon_sym_asc = 7,
  anon_sym_desc = 8,
  anon_sym_group = 9,
  anon_sym_distinct = 10,
  anon_sym_QMARK = 11,
  anon_sym_COLON = 12,
  anon_sym_PIPE = 13,
  anon_sym_AMP = 14,
  anon_sym_BANG = 15,
  anon_sym_LT_EQ = 16,
  anon_sym_EQ = 17,
  anon_sym_GT_EQ = 18,
  anon_sym_LT = 19,
  anon_sym_BANG_EQ = 20,
  anon_sym_GT = 21,
  anon_sym_in = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_POUND = 27,
  anon_sym_DOT = 28,
  anon_sym_AT = 29,
  anon_sym_LPAREN = 30,
  anon_sym_RPAREN = 31,
  anon_sym_this = 32,
  anon_sym_COLON_COLON = 33,
  sym_number = 34,
  anon_sym_DQUOTE = 35,
  sym_char_literal = 36,
  sym_char_escaped = 37,
  sym_expression = 38,
  sym_expression_filter = 39,
  sym_expression_which = 40,
  sym_expression_map = 41,
  sym_expression_limit = 42,
  sym_expression_order = 43,
  sym_expression_group = 44,
  sym_expression_distinct = 45,
  sym_expression_conditional = 46,
  sym_expression_binary = 47,
  sym_expression_unary = 48,
  sym_expression_count = 49,
  sym_expression_property = 50,
  sym_expression_element = 51,
  sym_expression_id = 52,
  sym_expression_parentheses = 53,
  sym_expression_this = 54,
  sym_expression_name = 55,
  sym_string = 56,
  sym__char = 57,
  aux_sym_string_repeat1 = 58,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_where] = "where",
  [anon_sym_which] = "which",
  [anon_sym_map] = "map",
  [anon_sym_limit] = "limit",
  [anon_sym_order] = "order",
  [anon_sym_asc] = "asc",
  [anon_sym_desc] = "desc",
  [anon_sym_group] = "group",
  [anon_sym_distinct] = "distinct",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_BANG] = "!",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ] = "=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_in] = "in",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_POUND] = "#",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_this] = "this",
  [anon_sym_COLON_COLON] = "::",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_char_literal] = "char_literal",
  [sym_char_escaped] = "char_escaped",
  [sym_expression] = "expression",
  [sym_expression_filter] = "expression_filter",
  [sym_expression_which] = "expression_which",
  [sym_expression_map] = "expression_map",
  [sym_expression_limit] = "expression_limit",
  [sym_expression_order] = "expression_order",
  [sym_expression_group] = "expression_group",
  [sym_expression_distinct] = "expression_distinct",
  [sym_expression_conditional] = "expression_conditional",
  [sym_expression_binary] = "expression_binary",
  [sym_expression_unary] = "expression_unary",
  [sym_expression_count] = "expression_count",
  [sym_expression_property] = "expression_property",
  [sym_expression_element] = "expression_element",
  [sym_expression_id] = "expression_id",
  [sym_expression_parentheses] = "expression_parentheses",
  [sym_expression_this] = "expression_this",
  [sym_expression_name] = "expression_name",
  [sym_string] = "string",
  [sym__char] = "_char",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_where] = anon_sym_where,
  [anon_sym_which] = anon_sym_which,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_limit] = anon_sym_limit,
  [anon_sym_order] = anon_sym_order,
  [anon_sym_asc] = anon_sym_asc,
  [anon_sym_desc] = anon_sym_desc,
  [anon_sym_group] = anon_sym_group,
  [anon_sym_distinct] = anon_sym_distinct,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_this] = anon_sym_this,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_char_literal] = sym_char_literal,
  [sym_char_escaped] = sym_char_escaped,
  [sym_expression] = sym_expression,
  [sym_expression_filter] = sym_expression_filter,
  [sym_expression_which] = sym_expression_which,
  [sym_expression_map] = sym_expression_map,
  [sym_expression_limit] = sym_expression_limit,
  [sym_expression_order] = sym_expression_order,
  [sym_expression_group] = sym_expression_group,
  [sym_expression_distinct] = sym_expression_distinct,
  [sym_expression_conditional] = sym_expression_conditional,
  [sym_expression_binary] = sym_expression_binary,
  [sym_expression_unary] = sym_expression_unary,
  [sym_expression_count] = sym_expression_count,
  [sym_expression_property] = sym_expression_property,
  [sym_expression_element] = sym_expression_element,
  [sym_expression_id] = sym_expression_id,
  [sym_expression_parentheses] = sym_expression_parentheses,
  [sym_expression_this] = sym_expression_this,
  [sym_expression_name] = sym_expression_name,
  [sym_string] = sym_string,
  [sym__char] = sym__char,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_where] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_which] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_limit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_order] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_asc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_desc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_group] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_distinct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_this] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_char_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_which] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_map] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_limit] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_order] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_group] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_distinct] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_count] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_property] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_element] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_id] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_parentheses] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_this] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__char] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_condition = 1,
  field_direction = 2,
  field_false = 3,
  field_filter = 4,
  field_grouper = 5,
  field_id = 6,
  field_identifier = 7,
  field_index = 8,
  field_left = 9,
  field_limiter = 10,
  field_mapper = 11,
  field_operator = 12,
  field_orderer = 13,
  field_property = 14,
  field_right = 15,
  field_true = 16,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_direction] = "direction",
  [field_false] = "false",
  [field_filter] = "filter",
  [field_grouper] = "grouper",
  [field_id] = "id",
  [field_identifier] = "identifier",
  [field_index] = "index",
  [field_left] = "left",
  [field_limiter] = "limiter",
  [field_mapper] = "mapper",
  [field_operator] = "operator",
  [field_orderer] = "orderer",
  [field_property] = "property",
  [field_right] = "right",
  [field_true] = "true",
};

static const TSFieldMapSlice ts_field_map_slices[14] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 3},
  [10] = {.index = 14, .length = 1},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_left, 0},
    {field_operator, 1},
  [4] =
    {field_id, 2},
    {field_identifier, 0},
  [6] =
    {field_filter, 2},
  [7] =
    {field_mapper, 2},
  [8] =
    {field_limiter, 2},
  [9] =
    {field_orderer, 2},
  [10] =
    {field_grouper, 2},
  [11] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [14] =
    {field_property, 2},
  [15] =
    {field_index, 2},
  [16] =
    {field_direction, 3},
    {field_orderer, 2},
  [18] =
    {field_condition, 0},
    {field_false, 4},
    {field_true, 2},
};

static TSSymbol ts_alias_sequences[14][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '&') ADVANCE(10);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '|') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(33);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(22);
      if (lookahead == '&') ADVANCE(10);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == '-') ADVANCE(19);
      if (lookahead == '.') ADVANCE(23);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '<') ADVANCE(15);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '>') ADVANCE(17);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '|') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_char_literal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_char_literal);
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'b' ||
          lookahead == 'f' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == 'v') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_char_escaped);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'g') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'm') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'w') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_asc);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_desc);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(38);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_this);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'h') ADVANCE(43);
      END_STATE();
    case 38:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_group);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_limit);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_order);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_where);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_which);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_distinct);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_where] = ACTIONS(1),
    [anon_sym_which] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_limit] = ACTIONS(1),
    [anon_sym_order] = ACTIONS(1),
    [anon_sym_asc] = ACTIONS(1),
    [anon_sym_desc] = ACTIONS(1),
    [anon_sym_group] = ACTIONS(1),
    [anon_sym_distinct] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_this] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_char_escaped] = ACTIONS(1),
  },
  [1] = {
    [sym_expression] = STATE(50),
    [sym_expression_filter] = STATE(8),
    [sym_expression_which] = STATE(8),
    [sym_expression_map] = STATE(8),
    [sym_expression_limit] = STATE(8),
    [sym_expression_order] = STATE(8),
    [sym_expression_group] = STATE(8),
    [sym_expression_distinct] = STATE(8),
    [sym_expression_conditional] = STATE(8),
    [sym_expression_binary] = STATE(8),
    [sym_expression_unary] = STATE(8),
    [sym_expression_count] = STATE(8),
    [sym_expression_property] = STATE(8),
    [sym_expression_element] = STATE(8),
    [sym_expression_id] = STATE(8),
    [sym_expression_parentheses] = STATE(8),
    [sym_expression_this] = STATE(8),
    [sym_expression_name] = STATE(8),
    [sym_string] = STATE(8),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_distinct] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_this] = ACTIONS(11),
    [anon_sym_COLON_COLON] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(19), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [54] = 5,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(45), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 23,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [94] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(47), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [148] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(49), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [202] = 2,
    ACTIONS(53), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [236] = 3,
    ACTIONS(59), 1,
      anon_sym_POUND,
    ACTIONS(57), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 25,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [272] = 2,
    ACTIONS(63), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [306] = 2,
    ACTIONS(67), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [340] = 5,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(71), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 23,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_RPAREN,
  [380] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(73), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [434] = 6,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(71), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 21,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
  [476] = 7,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(71), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 19,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_RPAREN,
  [520] = 2,
    ACTIONS(77), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(75), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [554] = 2,
    ACTIONS(81), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(79), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [588] = 9,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(71), 1,
      anon_sym_BANG,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_RPAREN,
  [636] = 2,
    ACTIONS(85), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [670] = 9,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(69), 14,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_RPAREN,
  [718] = 10,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(69), 13,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_RPAREN,
  [768] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(87), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [822] = 13,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(89), 2,
      anon_sym_asc,
      anon_sym_desc,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(47), 9,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [878] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(91), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [932] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(93), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [986] = 12,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
    ACTIONS(95), 11,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_COLON,
      anon_sym_RPAREN,
  [1040] = 2,
    ACTIONS(99), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1074] = 2,
    ACTIONS(103), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1108] = 2,
    ACTIONS(107), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1142] = 2,
    ACTIONS(111), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1176] = 2,
    ACTIONS(115), 3,
      anon_sym_BANG,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 26,
      ts_builtin_sym_end,
      anon_sym_where,
      anon_sym_which,
      anon_sym_map,
      anon_sym_limit,
      anon_sym_order,
      anon_sym_asc,
      anon_sym_desc,
      anon_sym_group,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1210] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(11), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1259] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(21), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1308] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1357] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1406] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1455] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1504] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1553] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1602] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1651] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(20), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1700] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1749] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1798] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(5), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1847] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1896] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1945] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [1994] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [2043] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [2092] = 10,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(5), 1,
      anon_sym_distinct,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_this,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      sym_number,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(26), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(8), 18,
      sym_expression_filter,
      sym_expression_which,
      sym_expression_map,
      sym_expression_limit,
      sym_expression_order,
      sym_expression_group,
      sym_expression_distinct,
      sym_expression_conditional,
      sym_expression_binary,
      sym_expression_unary,
      sym_expression_count,
      sym_expression_property,
      sym_expression_element,
      sym_expression_id,
      sym_expression_parentheses,
      sym_expression_this,
      sym_expression_name,
      sym_string,
  [2141] = 18,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      anon_sym_where,
    ACTIONS(119), 1,
      anon_sym_which,
    ACTIONS(121), 1,
      anon_sym_map,
    ACTIONS(123), 1,
      anon_sym_limit,
    ACTIONS(125), 1,
      anon_sym_order,
    ACTIONS(127), 1,
      anon_sym_group,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
  [2203] = 18,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      anon_sym_where,
    ACTIONS(119), 1,
      anon_sym_which,
    ACTIONS(121), 1,
      anon_sym_map,
    ACTIONS(123), 1,
      anon_sym_limit,
    ACTIONS(125), 1,
      anon_sym_order,
    ACTIONS(127), 1,
      anon_sym_group,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
  [2265] = 18,
    ACTIONS(21), 1,
      anon_sym_QMARK,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(25), 1,
      anon_sym_AMP,
    ACTIONS(27), 1,
      anon_sym_BANG,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(117), 1,
      anon_sym_where,
    ACTIONS(119), 1,
      anon_sym_which,
    ACTIONS(121), 1,
      anon_sym_map,
    ACTIONS(123), 1,
      anon_sym_limit,
    ACTIONS(125), 1,
      anon_sym_order,
    ACTIONS(127), 1,
      anon_sym_group,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(31), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 5,
      anon_sym_LT_EQ,
      anon_sym_EQ,
      anon_sym_GT_EQ,
      anon_sym_BANG_EQ,
      anon_sym_in,
  [2327] = 4,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      sym_char_literal,
    ACTIONS(139), 1,
      sym_char_escaped,
    STATE(54), 2,
      sym__char,
      aux_sym_string_repeat1,
  [2341] = 4,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      sym_char_literal,
    ACTIONS(145), 1,
      sym_char_escaped,
    STATE(52), 2,
      sym__char,
      aux_sym_string_repeat1,
  [2355] = 4,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    ACTIONS(149), 1,
      sym_char_literal,
    ACTIONS(152), 1,
      sym_char_escaped,
    STATE(54), 2,
      sym__char,
      aux_sym_string_repeat1,
  [2369] = 1,
    ACTIONS(155), 1,
      sym_identifier,
  [2373] = 1,
    ACTIONS(157), 1,
      sym_identifier,
  [2377] = 1,
    ACTIONS(159), 1,
      sym_identifier,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 94,
  [SMALL_STATE(5)] = 148,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 236,
  [SMALL_STATE(8)] = 272,
  [SMALL_STATE(9)] = 306,
  [SMALL_STATE(10)] = 340,
  [SMALL_STATE(11)] = 380,
  [SMALL_STATE(12)] = 434,
  [SMALL_STATE(13)] = 476,
  [SMALL_STATE(14)] = 520,
  [SMALL_STATE(15)] = 554,
  [SMALL_STATE(16)] = 588,
  [SMALL_STATE(17)] = 636,
  [SMALL_STATE(18)] = 670,
  [SMALL_STATE(19)] = 718,
  [SMALL_STATE(20)] = 768,
  [SMALL_STATE(21)] = 822,
  [SMALL_STATE(22)] = 878,
  [SMALL_STATE(23)] = 932,
  [SMALL_STATE(24)] = 986,
  [SMALL_STATE(25)] = 1040,
  [SMALL_STATE(26)] = 1074,
  [SMALL_STATE(27)] = 1108,
  [SMALL_STATE(28)] = 1142,
  [SMALL_STATE(29)] = 1176,
  [SMALL_STATE(30)] = 1210,
  [SMALL_STATE(31)] = 1259,
  [SMALL_STATE(32)] = 1308,
  [SMALL_STATE(33)] = 1357,
  [SMALL_STATE(34)] = 1406,
  [SMALL_STATE(35)] = 1455,
  [SMALL_STATE(36)] = 1504,
  [SMALL_STATE(37)] = 1553,
  [SMALL_STATE(38)] = 1602,
  [SMALL_STATE(39)] = 1651,
  [SMALL_STATE(40)] = 1700,
  [SMALL_STATE(41)] = 1749,
  [SMALL_STATE(42)] = 1798,
  [SMALL_STATE(43)] = 1847,
  [SMALL_STATE(44)] = 1896,
  [SMALL_STATE(45)] = 1945,
  [SMALL_STATE(46)] = 1994,
  [SMALL_STATE(47)] = 2043,
  [SMALL_STATE(48)] = 2092,
  [SMALL_STATE(49)] = 2141,
  [SMALL_STATE(50)] = 2203,
  [SMALL_STATE(51)] = 2265,
  [SMALL_STATE(52)] = 2327,
  [SMALL_STATE(53)] = 2341,
  [SMALL_STATE(54)] = 2355,
  [SMALL_STATE(55)] = 2369,
  [SMALL_STATE(56)] = 2373,
  [SMALL_STATE(57)] = 2377,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_limit, 3, .production_id = 6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_unary, 2, .production_id = 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_unary, 2, .production_id = 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_order, 3, .production_id = 7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_conditional, 5, .production_id = 13),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_order, 4, .production_id = 12),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_order, 4, .production_id = 12),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_name, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_name, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_property, 3, .production_id = 10),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_property, 3, .production_id = 10),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_binary, 3, .production_id = 9),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_binary, 3, .production_id = 9),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_distinct, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_this, 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_this, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_name, 2),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_name, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_group, 3, .production_id = 8),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_map, 3, .production_id = 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_which, 3, .production_id = 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_filter, 3, .production_id = 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_id, 3, .production_id = 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_id, 3, .production_id = 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_parentheses, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_parentheses, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_element, 3, .production_id = 11),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_element, 3, .production_id = 11),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_count, 2, .production_id = 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_count, 2, .production_id = 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(54),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(54),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ql(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
